version: '3.1'

services:
  backend:
    build: ./back
    restart: no
    ports:
      - "3000:3000"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: test
      MONGO_URI: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - web
      - db
    volumes:
      - ./back:/app
    stdin_open: true # docker run -i
    tty: true
  frontend:
    build: ./front
    restart: always
    ports:
      - "80:80"
    environment:
        API_URL: http://backend:3000
    networks:
      - web
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    networks:
      - db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
    networks:
      - db
volumes:
  data:
networks:
  db:
  web:
